#! /usr/bin/env python
import sys

from crds.hst import locate
from crds import pysh

for line in open(sys.argv[1]):
    if not line.strip():
        continue
    file1, file2 = line.split()
    path1 = locate.locate_server_reference(file1)
    path2 = locate.locate_server_reference(file2)
    print "="*100
    out_err = pysh.out_err("python -m crds.diff $path1 $path2")
    print out_err
    print "-"*100
