#! /bin/tcsh

source env.csh

echo "Clearing reference database caches"
rm -f ../hst_refcache/*

echo "Clearing dataset database caches"
rm -f ../datasets/*.pkl  opus_bestrefs.err

echo "Dumping catalog datasets"
(python db_test.py dumpall;)

./regen |& tee regen.out

./get_opus_bestref testall.err.1 |& tee opus_bestrefs.err

./testall >& testall.err.2
grep -E 'errors|warn|datasets' testall.err.2 | grep -v -E 'pickle'

