#! /usr/bin/env python
#-*-python-*-

import sys

from crds import pysh

def summarize(file):
    return pysh.out_err("grep -E 'errors|warn|datasets' ${file} | grep -v -E pickle")

if "--help" in sys.argv or len(sys.argv) not in [1,2]:
    usage("[<testall.err.XXXX>]", 0, 1)
    sys.exit(-1)
elif len(sys.argv) == 2 and sys.argv[1] == "diff":
    out1 = summarize("testall.err.1")
    open("summarize.1", "w+").write(out1)
    out2 = summarize("testall.err.2")
    open("summarize.2", "w+").write(out2)
    pysh.sh("diff summarize.1 summarize.2")
    pysh.sh("rm summarize.[12]")
    sys.exit(0)
elif len(sys.argv) == 1:
    print summarize("testall.err.2")
else:
    print summarize(sys.argv[1])


