#! /bin/sh

for instr in acs cos stis wfc3 nicmos wfpc2
do 
	echo ======================== $instr =========================
    if [ "$1" != "" ] 
    then
       serial="_`printf %04d $1`"
    fi
	python -m crds.certify -H --verbose hst_${instr}${serial}.imap -t rmap       
done > certify_all.log

echo "============================================================"
echo "==================== summary ==============================="
echo "============================================================"
grep -E 'error|warn|Certifying' certify_all.log
