#! /bin/sh

for instr in acs cos stis wfc3 nicmos wfpc2
do 
	echo ======================== $instr =========================
	python -m crds.certify -H --verbose hst_${instr}.imap -t rmap $*
done | tee certify_all.log

echo "============================================================"
echo "==================== summary ==============================="
echo "============================================================"
grep -E 'error|warn|Certifying' certify_all.log
